CREATE TABLE `mh_qna` (
	`QNA_ID` int NOT NULL AUTO_INCREMENT,
  `USER_ID` varchar(30) NOT NULL,
  `DESIGNER_ID` varchar(30) NOT NULL,
  `QNA_CONTENTS` text,
  `QNA_SNO` int DEFAULT NULL,
  `QNA_LEV` int DEFAULT NULL,
  `UPPR_SNO` int DEFAULT NULL,
  `WRITE_DATE` datetime DEFAULT NULL,
  `UPDATE_DATE` datetime DEFAULT NULL,
  PRIMARY KEY (`QNA_ID`),
  CONSTRAINT `mh_qna_ibfk_1` FOREIGN KEY (`USER_ID`) REFERENCES `mh_user` (`USER_ID`) ON DELETE CASCADE
) ENGINE=InnoDB AUTO_INCREMENT=1 DEFAULT CHARSET=utf8 COMMENT='QNA';
