CREATE TABLE `mh_faq` (
  `FAQ_ID` int(11) NOT NULL AUTO_INCREMENT,
  `FAQ_TITLE` varchar(45) DEFAULT NULL,
  `FAQ_CONTENT` text,
  `USER_ID` varchar(45) DEFAULT NULL,
  `USER_NAME` varchar(45) DEFAULT NULL,
  `ATTACH_PATH` varchar(45) DEFAULT NULL,
  `ATTACH_NAME` varchar(45) DEFAULT NULL,
  `WRITE_DATE` datetime DEFAULT NULL,
  `UPDATE_DATE` datetime DEFAULT NULL,
  PRIMARY KEY (`FAQ_ID`)
) ENGINE=InnoDB AUTO_INCREMENT=1 DEFAULT CHARSET=utf8 COMMENT='FAQ';